apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beam-clip
  template:
    metadata:
      labels:
        app: beam-clip
    spec:
      containers:
      - name: beam-clip-container
        image: localhost:5001/beam-clip:latest
        securityContext:
          privileged: true
