name: Build and Release Clip CLI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goversion: ['1.20']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
        - os: ubuntu-latest
          ARCH: amd64
          PLATFORM: linux
        - os: macos-latest
          ARCH: amd64
          PLATFORM: darwin
        - os: windows-latest
          ARCH: amd64
          PLATFORM: windows

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go mod download
    - name: Build
      env:
        GOOS: ${{ matrix.PLATFORM }}
        GOARCH: ${{ matrix.ARCH }}
      run: go build -o /workspace/bin/clip /workspace/cmd/main.go
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.PLATFORM }}-clip
        path: /workspace/bin/clip
